#!/usr/bin/env python3
# vim:ts=2:sw=2:et:ai:sts=2

"""Wrapper around named-checkzone(1) accepting multiple zone files per run.

Useful for pre-commit hooks when all zone files are named after their zone.
"""

import argparse
import os
import re
import subprocess
import sys


def main() -> int:
  args = parse_args()
  retcode = 0

  for zonefile in args.zonefiles:
    zonename = re.sub(r"^db\.", "", os.path.basename(zonefile))
    checkzone_args = args.checkzone_opts + [zonename, zonefile]
    try:
      subprocess.check_call(["named-checkzone"] + checkzone_args)
    except subprocess.CalledProcessError:
      retcode += 1

  return retcode


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser()
  # fmt: off
  default_opts = [
    # TODO(dato): add --lints option instead of hardcoding these.
    "-k", "fail",
    "-m", "fail",
    "-M", "fail",
    "-n", "fail",
    "-r", "fail",
    "-S", "fail",
  ]
  # fmt: on

  parser.add_argument("zonefiles", metavar="zonefile", nargs="+")
  parser.add_argument(
    "--quiet",
    "-q",
    dest="checkzone_opts",
    action="append_const",
    const="-q",
    default=default_opts,
  )

  return parser.parse_args()


if __name__ == "__main__":
  sys.exit(main())
